apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - image: gcr.io/google-samples/gb-frontend:v4
        name: php-redis
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
          name: guestbook
    